### ISSUE TITLE
Add the function type to the new environment when typechecking the body.

### ISSUE THREAD

**Issue by ethanpailes** [tekknolagi/tigress#2]
https://github.com/tekknolagi/tigress/blob/e340d53611f8b2472c41f769aec6c188b30f157d/l02ast.ml#L139

Let's get those recursive functions going! I like being Turing complete.

**Comment by ethanpailes** [comment]
Also this: https://github.com/tekknolagi/tigress/blob/bb19a3395a3f3f362c6a00cb7a6311b52768160f/l03eval.ml#L39
for recursion.

**Comment by tekknolagi** [comment]
Hm, not sure I know how to do this. Lambdas do not have a name associated with them and all I have are lambdas:

```
let MyFun = \(X: Int) : Int = X + 5 in MyFun(3) end
```

**Comment by ethanpailes** [comment]
You're right. It is handled by let.

**Comment by tekknolagi** [comment]
Fixed in c41accb.
